-- File: add_gate.vhd
-- Generated by MyHDL 0.9.0
-- Date: Thu Apr 20 17:42:04 2017


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity add_gate is
    port (
        a: in std_logic;
        b: in std_logic;
        c: out std_logic;
        clk: in std_logic
    );
end entity add_gate;


architecture MyHDL of add_gate is






begin





ADD_GATE_LOGIC: process (clk) is
begin
    if rising_edge(clk) then
        c <= stdl(bool(a) and bool(b));
    end if;
end process ADD_GATE_LOGIC;

end architecture MyHDL;
