# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlinks', '0002_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skypedata',
            name='login',
        ),
        migrations.RemoveField(
            model_name='skypedata',
            name='password',
        ),
        migrations.AlterField(
            model_name='skypedata',
            name='chatName',
            field=models.CharField(default='Learning is an awesome journey', max_length=255),
        ),
    ]
